
export enum WEATHER_ACTIONS{
    GET_TEMPS="GET_TEMPS"
}

export enum NEWS_ACTIONS{
    GET_NEWS = "GET_NEWS",
    ADD_NEWS = "ADD_NEWS",
    DELETE_NEWS= "DELETE_NEWS",
    EDIT_NEWS= "EDIT_NEWS",

}


export enum COMMENT_ACTIONS{
    GET_COMMENT_ACTIONS = "GET_COMMENT_ACTIONS",
    ADD_COMMENT_ACTIONS = "ADD_COMMENT_ACTIONS",
    DELETE_COMMENT_ACTIONS= "DELETE_COMMENT_ACTIONS",
    EDIT_COMMENT_ACTIONS= "EDIT_COMMENT_ACTIONS",

}